### ISSUE TITLE
TypeError: a.call is not a function

### ISSUE THREAD

**Issue by rahuldamodar94** [maticnetwork/matic.js#141]
Error while calling the exit function for pos withdraw 

```
TypeError: a.call is not a function
    at e.exports (/Users/rahulprabhu/Documents/GitHub/pos-matic-demo/node_modules/@maticnetwork/maticjs/dist/matic.node.js:15:1706957)
    at t.<anonymous> (/Users/rahulprabhu/Documents/GitHub/pos-matic-demo/node_modules/@maticnetwork/maticjs/dist/matic.node.js:8:26133)
    at /Users/rahulprabhu/Documents/GitHub/pos-matic-demo/node_modules/@maticnetwork/maticjs/dist/matic.node.js:8:23422
    at Object.next (/Users/rahulprabhu/Documents/GitHub/pos-matic-demo/node_modules/@maticnetwork/maticjs/dist/matic.node.js:8:23527)
    at r (/Users/rahulprabhu/Documents/GitHub/pos-matic-demo/node_modules/@maticnetwork/maticjs/dist/matic.node.js:8:22241)
  ```

**Comment by jdkanani** [comment]
This bug was introduced in `v2.0.17`
