### ISSUE TITLE
Examples. POS-Client / Ether fails with BUFFER OVERRUN error code

### ISSUE THREAD

**Issue by freebyte** [maticnetwork/matic.js#183]
Error:

```
worker@lenovo ~/Documents/MyProjects/etherium/POS-client/Ether $ node exit.js 
Error: data out-of-bounds (length=3, offset=32, code=BUFFER_OVERRUN, version=abi/5.0.7)
    at Logger.makeError (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@ethersproject/logger/lib/index.js:180:21)
    at Logger.throwError (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@ethersproject/logger/lib/index.js:189:20)
    at Reader._peekBytes (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:149:24)
    at Reader.readBytes (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:161:26)
    at Reader.readValue (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:167:48)
    at NumberCoder.decode (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@ethersproject/abi/lib/coders/number.js:49:28)
    at /home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@ethersproject/abi/lib/coders/array.js:106:31
    at Array.forEach (<anonymous>)
    at Object.unpack (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@ethersproject/abi/lib/coders/array.js:85:12)
    at TupleCoder.decode (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@ethersproject/abi/lib/coders/tuple.js:39:49)
    at AbiCoder.decode (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@ethersproject/abi/lib/abi-coder.js:93:22)
    at ABICoder.decodeParametersWith (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/web3-eth-abi/lib/index.js:304:30)
    at ABICoder.decodeParameters (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/web3-eth-abi/lib/index.js:285:17)
    at Contract._decodeMethodReturn (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/web3-eth-contract/lib/index.js:470:22)
    at Method.outputFormatter (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/web3-eth-contract/lib/index.js:760:42)
    at Method.formatOutput (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/web3-core-method/lib/index.js:147:54)
    at sendTxCallback (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/web3-core-method/lib/index.js:523:33)
    at /home/worker/Documents/MyProjects/etherium/POS-client/node_modules/web3-core-requestmanager/lib/index.js:308:9
    at /home/worker/Documents/MyProjects/etherium/POS-client/node_modules/@trufflesuite/web3-provider-engine/index.js:240:9
    at /home/worker/Documents/MyProjects/etherium/POS-client/node_modules/async/internal/once.js:12:16
    at replenish (/home/worker/Documents/MyProjects/etherium/POS-client/node_modules/async/internal/eachOfLimit.js:61:25)
    at /home/worker/Documents/MyProjects/etherium/POS-client/node_modules/async/internal/eachOfLimit.js:71:9 {
  reason: 'data out-of-bounds',
  code: 'BUFFER_OVERRUN',
  length: 3,
  offset: 32
}
```

How to reproduce:

1. Run deposit.js

```
worker@lenovo ~/Documents/MyProjects/etherium/POS-client/Ether $ node deposit.js 
0x7b5a6c05bef2ac8008b09f699250e6f16eec2d8f4d526592de1d08642d477c3d
```

2. Run burn.js

```
worker@lenovo ~/Documents/MyProjects/etherium/POS-client/Ether $ node burn.js 
0xac77350551b6eaee6f09d77e3cf7ca03258dfeb7f86368ad85684dec4dd7a6aa
```

3. Edit exit.js to insert 0xac77350551b6eaee6f09d77e3cf7ca03258dfeb7f86368ad85684dec4dd7a6aa from the previous step. Then run
```
worker@lenovo ~/Documents/MyProjects/etherium/POS-client/Ether $ node exit.js 
```

The above error follows.

**Comment by will-holley** [comment]
Can't reproduce without those scripts.
