### ISSUE TITLE
Error: Cannot find module './mainnet/mumbai/index.json'

### ISSUE THREAD

**Issue by miguelmota** [maticnetwork/matic.js#202]
Hi, I'm getting the error `Error: Cannot find module './mainnet/mumbai/index.json'` when using `network: 'mainnet'` config with `MaticPOSClient`. It works however when using `network: 'testnet'`.

Set up:

```js
import { MaticPOSClient } from '@maticnetwork/maticjs'

const maticPOSClient = new MaticPOSClient({
  network: 'mainnet',
  maticProvider: new Web3.providers.HttpProvider(
    'https://rpc-mainnet.maticvigil.com'
  ),
  parentProvider: new Web3.providers.HttpProvider(
    'https://mainnet.infura.io/...'
  ),
  posRootChainManager: '0xA0c68C638235ee32657e8f720a23ceC1bFc77C77',
  posERC20Predicate: '0x40ec5B33f54e0E8A33A975908C5BA1c14e5BbbDf'
})
```

Error:

```bash
{ Error: Cannot find module './mainnet/mumbai/index.json'
    at s (/home/mota/Sandbox/hop/monorepo/packages/hop-node/node_modules/@maticnetwork/maticjs/dist/matic.node.js:15:105460)
    at i (/home/mota/Sandbox/hop/monorepo/packages/hop-node/node_modules/@maticnetwork/maticjs/dist/matic.node.js:15:105409)
    at new i (/home/mota/Sandbox/hop/monorepo/packages/hop-node/node_modules/@maticnetwork/maticjs/dist/matic.node.js:15:104854)
    at Function.t.initializeNetwork (/home/mota/Sandbox/hop/monorepo/packages/hop-node/node_modules/@maticnetwork/maticjs/dist/matic.node.js:15:102223)
    at new t (/home/mota/Sandbox/hop/monorepo/packages/hop-node/node_modules/@maticnetwork/maticjs/dist/matic.node.js:15:87121)
    at polygonBridgeWatcher.getPayload (/home/mota/Sandbox/hop/monorepo/packages/hop-node/dist/src/watchers/polygonBridgeWatcher.js:108:32)
    at processTicksAndRejections (internal/process/task_queues.js:86:5) code: 'MODULE_NOT_FOUND' }
```

Version:

```json
    "@maticnetwork/maticjs": "^2.0.40"
```

Any ideas on how to make it work with mainnet?  Thanks in advance.

**Comment by miguelmota** [comment]
Alright, so the issue was that the sdk requires the config option `version: 'v1'`. 


```js
import { MaticPOSClient } from '@maticnetwork/maticjs'

const maticPOSClient = new MaticPOSClient({
  network: 'mainnet',
  version: 'v1',
  maticProvider: new Web3.providers.HttpProvider(
    'https://rpc-mainnet.maticvigil.com'
  ),
  parentProvider: new Web3.providers.HttpProvider(
    'https://mainnet.infura.io/...'
  ),
  posRootChainManager: '0xA0c68C638235ee32657e8f720a23ceC1bFc77C77',
  posERC20Predicate: '0x40ec5B33f54e0E8A33A975908C5BA1c14e5BbbDf'
})
```

Would be nice to default to `v1` if network is `mainnet`. 

Closing since it's resolved.
