### ISSUE TITLE
Name export 'use' not found.

### ISSUE THREAD

**Issue by jc911** [maticnetwork/matic.js#334]
### I refer to this doc
https://docs.polygon.technology/docs/develop/ethereum-polygon/matic-js/get-started

#### My js code:
```js
import { use } from '@maticnetwork/maticjs'
import { Web3ClientPlugin } from '@maticnetwork/maticjs-web3'

// install web3 plugin
use(Web3ClientPlugin)
```

#### Terminal return:
```zsh
polygonweb3 % node polygon.js
file://polygonweb3/polygon.js:1
import { use } from '@maticnetwork/maticjs'
         ^^^
SyntaxError: Named export 'use' not found. The requested module '@maticnetwork/maticjs' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@maticnetwork/maticjs';
const { use } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

#### Hint

* I have add {"type": "module"} in my package.json

**Comment by ujjwalgupta94** [comment]
Are you using in node.js code ? if yes please use `require` syntax.

**Comment by jc911** [comment]
> Are you using in node.js code ? if yes please use `require` syntax.

Yes! Thank you!
Another question, do you know how to run the code in the doc?
What environment do I need to run code like this?
```javascript
import { POSClient,use } from "@maticnetwork/maticjs"
import { Web3ClientPlugin } from '@maticnetwork/maticjs-web3'
import HDWalletProvider from "@truffle/hdwallet-provider"

// install web3 plugin
use(Web3ClientPlugin);

const posClient = new POSClient();
await posClient.init({
    network: 'testnet',
    version: 'mumbai',
    parent: {
      provider: new HDWalletProvider(privateKey, mainRPC),
      defaultConfig: {
        from : fromAddress
      }
    },
    child: {
      provider: new HDWalletProvider(privateKey, childRPC),
      defaultConfig: {
        from : fromAddress
      }
    }
});
```

**Comment by ujjwalgupta94** [comment]
hey you need to just add `.env` file similar to `.env.example` file
