### ISSUE TITLE
WithdrawExit doesn't work

### ISSUE THREAD

**Issue by dellwatson** [maticnetwork/matic.js#335]
**Describe the bug**
The tx has been checkpointed, but unable to validate the proof?

```js
 context: {
    code: -32603,
    message: 'ESOCKETTIMEDOUT',
    data: { originalError: { code: 'ESOCKETTIMEDOUT', connect: false } },
    stack: 'Error: ESOCKETTIMEDOUT\n' +
      '    at ClientRequest.<anonymous> (/Users/dellwatson/Desktop/avarik/matic.js/examples/node_modules/request/request.js:816:19)\n' +
      '    at Object.onceWrapper (events.js:420:28)\n' +
      '    at ClientRequest.emit (events.js:314:20)\n' +
      '    at TLSSocket.emitRequestTimeout (_http_client.js:715:9)\n' +
      '    at Object.onceWrapper (events.js:420:28)\n' +
      '    at TLSSocket.emit (events.js:326:22)\n' +
      '    at TLSSocket.Socket._onTimeout (net.js:483:8)\n' +
      '    at listOnTimeout (internal/timers.js:554:17)\n' +
      '    at processTimers (internal/timers.js:497:7)'
  }
  ```

**Comment by dellwatson** [comment]
wow Just checked the  answer from #315 
changing the mumbai's rpc solve the issue
