### ISSUE TITLE
Cannot read properties of undefined (reading 'PolygonZkEVMBridge')

### ISSUE THREAD

**Issue by qiushui777** [maticnetwork/matic.js#423]
**Describe the bug**
when trying to init zkEvmClient, it gives me error of "Cannot read properties of undefined (reading 'PolygonZkEVMBridge')"

#### Hint

```
const { ZkEvmClient, use } = require('@maticnetwork/maticjs')
const HDWalletProvider = require('@truffle/hdwallet-provider')
const { Web3ClientPlugin } = require('@maticnetwork/maticjs-web3')
const fs = require("fs")
var ini = require("ini")
use(Web3ClientPlugin)

var constant = fs.readFileSync("constant.ini").toString()
var info = ini.parse(constant);

const polygonrpc = info['param'].polygonendpoint
const gethrpc = info['param'].ethendpoint



const args = process.argv.slice(2)

tokenaddr = args[0]
txhash = args[1]

const getClient = async(network = 'mainnet', version = 'v1') => {

  const zkEvmClient = new ZkEvmClient();

  await zkEvmClient.init({
    network: 'mainnet',  // 'testnet'
    version: 'v1', // 'blueberry'

    child: {
      provider: new HDWalletProvider("", polygonrpc),
      defaultConfig: {
        from: "0x",
      },
    },
    parent: {
      provider: new HDWalletProvider("", gethrpc),
      defaultConfig: {
        from: "0x",
      },
    },

  });

}







const execute_slow = async (tokenaddr, txhash) => {
  // console.log("slow")
  const client = await getClient();

}



execute_slow(tokenaddr, txhash).then((exitCalldata) => {

  console.log(exitCalldata)


}).catch(err => {
  console.error("err", err);
}).finally(_ => {
  process.exit(0);
})
```

here is the script result

```
node zkprovebyte.js 
err TypeError: Cannot read properties of undefined (reading 'PolygonZkEVMBridge')
    at /root/node_modules/@maticnetwork/maticjs/dist/matic.node.js:5225:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getPOSClient (/root/dev/qscrosschainarb/zkprovebyte.js:25:3)
    at async execute_slow (/root/dev/qscrosschainarb/zkprovebyte.js:54:18)
```

**Comment by nitinmittal23** [comment]
For mainnet in zkEVM. the version is `cherry`. 
All the supported networks and versions can be found here https://github.com/maticnetwork/static/tree/master/network
